services:
  web:
    image: nginx:1.25
    depends_on:
      - back
    container_name: web
    volumes:
      #- ./Maconduite_frontend/build/:/usr/share/nginx/html/
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    networks:
      - networkapp
  back:
    build: ./
    depends_on:
      - db
    container_name: back
    #command: gunicorn --bind 0.0.0.0:8000 --workers 2 "dockerdjango.wsgi:application"
    #command: >
      #sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - app:/etc/app
    networks:
      - networkapp
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      #- POSTGRES_USER=MICHEL
      #- POSTGRES_PASSWORD=MICHELPOSTGRES
      #- POSTGRES_DB=MACONDUITE
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      - networkapp
volumes:
  app:
  postgres_data:
networks:
  networkapp:
    